package app_errors

var (
	ErrGameNotFound                                         = NewNotFoundError("game")
	ErrStaleGame                                            = NewStaleObjectError("game")
	ErrPlayerNotFound                                       = NewNotFoundError("player")
	ErrTerrainNotFound                                      = NewNotFoundError("terrain")
	ErrGameHasFullPlayers                                   = NewBusinessRuleError("game-has-full-players")
	ErrYouAlreadyJoined                                     = NewBusinessRuleError("you-already-joined")
	ErrYouAreNotInTurn                                      = NewBusinessRuleError("you-are-not-in-turn")
	ErrGameHasNotStartedYet                                 = NewBusinessRuleError("game-has-not-started-yet")
	ErrGameAlreadyStarted                                   = NewBusinessRuleError("game-already-started")
	ErrGameAlreadyFinished                                  = NewBusinessRuleError("game-already-finished")
	ErrYouAreUnableToPerformThisActionInCurrentPhase        = NewBusinessRuleError("you-are-unable-to-perform-this-action-in-current-phase")
	ErrSelectedLandHasBeenOccupied                          = NewBusinessRuleError("selected-land-has-been-occupied")
	ErrSelectedLandMustBeAdjacentWithYourRoad               = NewBusinessRuleError("selected-land-must-be-adjacent-with-your-road")
	ErrSelectedPathHasBeenOccupied                          = NewBusinessRuleError("selected-path-has-been-occupied")
	ErrSelectedPathMustBeAdjacentWithYourConstructionOrRoad = NewBusinessRuleError("selected-path-must-be-adjacent-with-your-construction-or-road")
	ErrNearbyLandsMustBeVacant                              = NewBusinessRuleError("nearby-lands-must-be-vacant")
	ErrSelectedLandAndPathMustBeAdjacent                    = NewBusinessRuleError("selected-land-and-path-must-be-adjacent")
	ErrYouHaveRunOutOfRoads                                 = NewBusinessRuleError("you-have-run-out-of-roads")
	ErrYouHaveRunOutOfSettlements                           = NewBusinessRuleError("you-have-run-out-of-settlements")
	ErrYouHaveRunOutOfCities                                = NewBusinessRuleError("you-have-run-out-of-cities")
	ErrYouHaveInsufficientResourceCards                     = NewBusinessRuleError("you-have-insufficient-resource-cards")
	ErrYouAlreadyRolledDices                                = NewBusinessRuleError("you-already-rolled-dices")
	ErrRobberMustBeMovedToOtherTerrain                      = NewBusinessRuleError("robber-must-be-moved-to-other-terrain")
	ErrRobberIsNotAvailableToMove                           = NewBusinessRuleError("robber-is-not-available-to-move")
	ErrYouCannotRobYourself                                 = NewBusinessRuleError("you-cannot-rob-yourself")
	ErrSelectedPlayerMustHaveConstructionNextToRobber       = NewBusinessRuleError("selected-player-must-have-construction-next-to-robber")
	ErrYouMustRobPlayerWhoHaveConstructionNextToRobber      = NewBusinessRuleError("you-must-rob-player-who-have-construction-next-to-robber")
	ErrYouMustRollDices                                     = NewBusinessRuleError("you-must-roll-dices")
	ErrSelectedConstructionAlreadyUpgraded                  = NewBusinessRuleError("selected-construction-already-upgraded")
	SelectedConstructionDoesNotBelongToAnyLand              = NewBusinessRuleError("selected-construction-does-not-belong-to-any-land")
	ErrGameHasRunOutOfDevelopmentCards                      = NewBusinessRuleError("game-has-run-out-of-development-cards")
)
